---
deployment:
  tasks:
    - export DEPLOYPATH=/home/breavira/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R styles.css $DEPLOYPATH
    - /bin/cp -R contact-confirmation.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH